[project]
name = "app-python"
version = "0.0.1"
authors = [{ name = "John Doe", email = "john.doe@whoknows.com" }]


[tool.ruff]
line-length = 120

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
